steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/flutter", "."]

  - name: "gcr.io/$PROJECT_ID/flutter"
    args: ["doctor"]

images: ["gcr.io/$PROJECT_ID/flutter"]
